name: Backfill Historical Prices (no trades)

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: "Number of daily bars to fetch (e.g. 1500–2000 for 3–5y)"
        required: false
        default: "1900"
      intraday_days_back_5m:
        description: "Number of days of 5m bars (if supported by fetch_prices)"
        required: false
        default: "180"
      news_lookback_days:
        description: "News lookback window (days) for this run"
        required: false
        default: "7"

permissions:
  contents: write

env:
  # Backtest-specific outputs so we don't clobber live files
  OUTPUT_PATH: data/prices_backtest.json

concurrency:
  group: backfill-prices-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backfill-prices-and-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.2.2 numpy==1.26.4 requests==2.32.3 \
                      python-dateutil==2.9.0.post0 feedparser==6.0.11 \
                      vaderSentiment==3.3.2 pyyaml==6.0.2
          pip install -r requirements.txt || echo "requirements.txt already satisfied."

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> "$GITHUB_ENV"

      - name: Backfill prices (daily + 5m)
        env:
          ALPACA_KEY_ID:     ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_DATA_FEED:  iex
          SYMBOLS_PATH:      data/symbols.txt
          OUTPUT_PATH:       ${{ env.OUTPUT_PATH }}
          DAYS_BACK:         ${{ github.event.inputs.days_back || '1900' }}
          INTRADAY_DAYS_BACK_5M: ${{ github.event.inputs.intraday_days_back_5m || '180' }}
        run: |
          echo "Fetching historical prices with DAYS_BACK=${DAYS_BACK}, INTRADAY_DAYS_BACK_5M=${INTRADAY_DAYS_BACK_5M}"
          python fetch_prices.py

      - name: Quick sanity check (prices)
        run: |
          if [[ -f "data/prices_backtest.json" ]]; then
            echo "as_of_utc:" $(jq -r '.as_of_utc' data/prices_backtest.json)
            echo "symbols:"   $(jq '.symbols|keys|length' data/prices_backtest.json)
          else
            echo "data/prices_backtest.json not found" >&2
            exit 1
          fi

      - name: Fetch news for backtest file
        env:
          INPUT_PATH:  data/prices_backtest.json
          OUTPUT_PATH: data/prices_backtest.json
          NEWS_LOOKBACK_DAYS:         ${{ github.event.inputs.news_lookback_days || '7' }}
          NEWS_LIMIT_PER_SYMBOL:      "25"
          NEWS_SOURCES:               "benzinga,mtnewswires,google_rss,finnhub,reddit"
          NEWSAPI_KEY:                ${{ secrets.NEWSAPI_KEY }}
          FINNHUB_KEY:                ${{ secrets.FINNHUB_KEY }}
          ALPACA_KEY_ID:              ${{ secrets.ALPAcA_KEY_ID }}
          ALPACA_SECRET_KEY:          ${{ secrets.ALPACA_SECRET_KEY }}
          USE_FINBERT:                "1"
          FINBERT_TRIGGER:            "0.20"
          FINBERT_FRACTION:           "0.30"
        run: |
          echo "Fetching news with NEWS_LOOKBACK_DAYS=${NEWS_LOOKBACK_DAYS} into prices_backtest.json"
          python scripts/fetch_news.py

      - name: Quick sanity check (news)
        run: |
          echo "news items in backtest base:" $(jq '[.symbols[]|.news?|length]|add' data/prices_backtest.json)

      - name: Commit & push backfilled prices+news (optional)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase --autostash origin ${{ github.ref_name }}
          git add data/prices_backtest.json || true
          git commit -m "Backfill: historical prices + recent news for backtesting" || echo "No changes."
          git push
